import asyncio
from typing import Dict, Tuple

from openai import AsyncOpenAI, OpenAI
from transformers import AutoTokenizer, PreTrainedTokenizerBase


def build_rerank_context_block(
    prompt_mode: str,
    overall_query: str,
    sub_query: str,
    reasoning: str | None,
) -> str:
    """Build the variable context section based on ``prompt_mode``."""
    parts: list[str] = []

    if prompt_mode in ("query_sub", "all_three"):
        parts.append("Overall Research Query (as context):")
        parts.append(overall_query)
        parts.append("")

    if prompt_mode in ("query_sub", "sub_only", "sub_reason", "all_three"):
        parts.append(
            "Current Sub-Query (generated by the agent, as the target query):"
        )
        parts.append(sub_query)
        parts.append("")

    if prompt_mode in ("sub_reason", "all_three") and reasoning:
        parts.append("Agent's reasoning so far:")
        parts.append(reasoning)
        parts.append("")

    return "\n".join(parts).rstrip()


class VllmHandlerWithOpenAISDK:
    def __init__(
        self,
        base_url: str,
        model: str | None = None,
    ):
        # async client for inference, but no awaiting here
        self._client = AsyncOpenAI(api_key="", base_url=base_url)

        # if model isn't provided, use the SYNC client to list models
        if model is None:
            sync = OpenAI(api_key="", base_url=base_url)
            models = sync.models.list()
            if not models.data:
                raise RuntimeError("No models available from vLLM /v1/models.")
            model = models.data[0].id

        self._model = model
        self._tokenizer = AutoTokenizer.from_pretrained(model)

    def get_tokenizer(self) -> PreTrainedTokenizerBase:
        return self._tokenizer

    async def async_inference(
        self, messages: list[dict[str, str]], **kwargs
    ) -> Tuple[str, Dict[str, int]]:
        assert isinstance(messages, list)
        assert isinstance(messages[0], dict)
        response = None
        try:
            response = await self._client.responses.create(
                model=self._model,
                input=messages,
                **kwargs,
            )
            response_dict = response.model_dump(mode="python")
            text = ""
            for item in response_dict.get("output", []):
                if item.get("type") == "message":
                    for part in item.get("content", []):
                        if part.get("type") in ["text", "output_text"]:
                            text += part.get("text", "")
            toks = response.usage.model_dump(mode="json")
            return text, toks
        except Exception as e:
            if response is not None:
                print(f"vLLM Response at error: {response}")
            print(f"vLLM inference error: {e}")
            return "", {}

    def inference(
        self, messages: list[dict[str, str]], **kwargs
    ) -> Tuple[str, Dict[str, int]]:
        return asyncio.run(self.async_inference(messages, **kwargs))
